export type ErrorCode =
  | 'MISSING_FILE'
  | 'MALFORMED_FILE'
  | 'MISSING_PROPERTY'
  | 'MISSING_PROPERTIES'
  | 'INVALID_VALUES'
  | 'INVALID_VALUE'
  | 'MISSING_VALUE'
  | 'INVALID_FILE_EXTENSION'
  | 'GENERATE_OPERATION_DENIED'
  | 'INVALID_PATH'
  | 'INSUFFICIENT_PERMISSIONS'
  | 'INVALID_ARGUMENT';
