name: CI for feature branches on PR creation

# Controls when the workflow will run
on:
  # Triggers the workflow on opened pull request events but only for the "develop" branch
  pull_request:
    branches:
      - develop
    types: ["opened", "edited"]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  provardx-ci-execution:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - uses: actions/setup-node@v4
        with:
          node-version: 18
      - name: 'Cache node_modules'
        uses: actions/cache@v3
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-v18-${{ hashFiles('**/package.json') }}
          restore-keys: |
            ${{ runner.os }}-node-v18-
      - name: Install Dependencies
        run: npm install
      - name: Build the project
        run: yarn prepack
      - name: Run NUTS Tests
        run: yarn run test:nuts
          
