name: CI for feature branches on PR creation

# Controls when the workflow will run
on:
  # Triggers the workflow on opened pull request events but only for the "develop" branch
  pull_request:
    branches:
      - develop
    types: ["opened", "edited"]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  provardx-ci-execution:
    strategy:
      matrix:
        os: [macos-latest, windows-latest, ubuntu-latest]
        nodeversion: [18]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.nodeversion }}
      - name: 'Cache node_modules'
        uses: actions/cache@v3
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-v${{ matrix.nodeversion }}-${{ hashFiles('**/package.json') }}
          restore-keys: |
            ${{ runner.os }}-node-v${{ matrix.nodeversion }}-
      - name: Install Dependencies
        run: |
          yarn
      - name: Build the project
        run: |
          yarn prepack
          npm install -g @salesforce/cli
      - name: Install plugin and execute NUTS
        run:   |
         if [ "$RUNNER_OS" == "Linux" ]; then
              sf plugins link .
              chmod 777 ./bin/run
              yarn run test:nuts
         elif [ "$RUNNER_OS" == "Windows" ]; then
              sf plugins link .
              yarn run test:nuts
         elif [ "$RUNNER_OS" == "macOS" ]; then
              sf plugins link .
              chmod 777 ./bin/run
              yarn run test:nuts
         else
              echo "$RUNNER_OS not supported"
              exit 1
         fi
        shell: bash
      - name: Archive NUTS results
        uses: actions/upload-artifact@v3
        with:
          name: nuts-report
          path: |
             mochawesome-report
          
