name: tests
on:
  push:
    branches-ignore: [main]
  workflow_dispatch:

jobs:
  yarn-lockfile-check:
    uses: salesforcecli/github-workflows/.github/workflows/lockFileCheck.yml@main
  # Since the Windows unit tests take much longer, we run the linux unit tests first and then run the windows unit tests in parallel with NUTs
  nuts:
    uses: salesforcecli/github-workflows/.github/workflows/nut.yml@main
    needs: yarn-lockfile-check
    secrets: inherit
    strategy:
      matrix:
        os: [ubuntu-latest]
        command:
          - export TESTKIT_EXECUTABLE_PATH='./node_modules/.bin/sf' && ./node_modules/.bin/sf plugins link . && yarn test:nuts
      fail-fast: false
    with:
      os: ${{ matrix.os }}
      command: ${{ matrix.command }}
